name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Ensure the action can push back using the provided token
          persist-credentials: true
          # Fetch full history so the action can create commits/tags if needed
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Check Node and npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare SPA fallback (copy index.html -> 404.html)
        run: |
          if [ -f ./dist/index.html ]; then
            cp ./dist/index.html ./dist/404.html
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # optional: set publish_branch: gh-pages
